export const START_NEW_GAME = 'START_NEW_GAME';
export const GO_TO_NEXT_TURN = 'GO_TO_NEXT_TURN';
export const CALL_COYOTE = 'CALL_COYOTE';
export const CHANGE_CALL_NUMBER = 'CHANGE_CALL_NUMBER';
export const CALL_NUMBER = 'CALL_NUMBER';
export const REFRESH_DISPLAY_STATE = 'REFRESH_DISPLAY_STATE';
export const ON_FOCUS_NUMBER_INPUT = 'ON_FOCUS_NUMBER_INPUT';
export const UPDATE_TIMER = 'UPDATE_TIMER';
